# This is a basic workflow to help you get started with Actions

name: dev_release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        default: 'NONE'
        description: Version change
        options:
        - NONE
        - BUILD_NUMBER
        - MAJOR
        - MINOR
        - PATCH
      note:
        type: string
        description: 'Release note'
        required: true
      feature:
        type: boolean
        description: For feature test

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # - name: Xcode list
    #   run: ls -n /Applications/ | grep Xcode*

    # - name: Select Xcode
    #   run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app

    # - name: Xcode version
    #   run: /usr/bin/xcodebuild -version

    - name: Inputs
      run: echo "Version change:${{ inputs.version }}\nRelease note:${{ inputs.note }}\nIs Feature build:${{ inputs.feature-build }}"

    - name: Build
      run: echo "release_dev from_ci:true is_feature:${{ inputs.feature-build }} release_notes:${{ inputs.note }} version_change_type:${{ inputs.version }}"
      
    
