# This is a basic workflow to help you get started with Actions

name: dev_release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        default: 'NONE'
        description: Version change
        options:
        - NONE
        - BUILD_NUMBER
        - MAJOR
        - MINOR
        - PATCH
      note:
        type: string
        description: 'Release note'
        required: true
      is-feature:
        type: boolean
        description: For feature test

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # - name: Xcode list
    #   run: ls -n /Applications/ | grep Xcode*

    # - name: Select Xcode
    #   run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app

    # - name: Xcode version
    #   run: /usr/bin/xcodebuild -version

    - name: Inputs
      run: |
        GREEN='\033[0;32m'
        RESET='\033[0m'
        
        echo "Version change: ${GREEN}${{ inputs.version }}${RESET}"
        echo "Release note: ${GREEN}${{ inputs.note }}${RESET}"
        echo "Is Feature build: ${GREEN}${{ inputs.is-feature }}${RESET}"
      
    - name: Build
      run: echo "release_dev from_ci:true is_feature:${{ inputs.is-feature }} release_notes:${{ inputs.note }} version_change_type:${{ inputs.version }}"
      
    
